### ISSUE TITLE
Dan, Please help to generate UWP project for Visual Studio IDE

### ISSUE THREAD

**Issue by mediaexplorer74** [deathkiller/jazz2-native#5]
[Dan](https://github.com/deathkiller), hi! Sorry for disturbing you.
I have special VS 2022 Preview edition, not 2019 stable. And I have not enough free space on my oldest notebook, so no CMake installed.  I think BuildUWP.bat will generate a tons of errors :(
Please help to generate UWP project for Visual Studio... if you can :)
Best wishes,
[m][e]

**Comment by deathkiller** [comment]
CMake is really required for UWP development, otherwise I'd have to send you new UWP project with every change I make. It has also other dependencies, like UWP SDK, Angle library and so on, which are not included yet, so it takes some effort to build it yourself. And UWP version is not 100% complete, so it's really not playable yet anyway. So I'm sorry, but I can't help you.

**Comment by mediaexplorer74** [comment]
> CMake is really required for UWP development, otherwise I'd have to send you new UWP project with every change I make. It has also other dependencies, like UWP SDK, Angle library and so on, which are not included yet, so it takes some effort to build it yourself. And UWP version is not 100% complete, so it's really not playable yet anyway. So I'm sorry, but I can't help you.

Ok. NP (no problem). 
Anyways, thank you for answering.
Best wishes to you and your UWP 'Jazz2 remake' :)

**Comment by mediaexplorer74** [comment]
> 

Hey,

I noticed that you "generated" VS solution for UWP version. Very nice! Great work. Thank you very much, Dan!
